-- Seed script for Interviews and QAOfInterview tables
-- Assumes user_id = 1 exists in the users table

-- Interview 1: Software Engineering Internship at Google (score 7)
INSERT INTO interviews (user_id, typeofinterview, institution, score, interview_date)
VALUES (1, 'internship', 'Google', 7, '2026-03-21');

INSERT INTO QAOfInterview (interview_id, chat, feedback)
 VALUES (
  (SELECT id FROM interviews WHERE user_id = 1 AND institution = 'Google' AND score = 7),
  '[{"speaker":"Gemini","text":"Hi there! I''m Alex, a senior engineer here at Google. Thanks for taking the time to interview for our Software Engineering Internship. I''m really looking forward to learning more about you. To kick things off, could you tell me a bit about your background and what drew you to software engineering?\n"},{"speaker":"User","text":"Yeah, absolutely. So I''m currently a third year computer science student. I got into coding through a hackathon in my first year and since then I''ve been really passionate about building full stack applications. I''ve done a couple of personal projects including a real time chat app and a portfolio site."},{"speaker":"Gemini","text":"That''s great to hear! A real-time chat app is no small feat. Can you walk me through a technical challenge you faced while building it and how you overcame it?\n"},{"speaker":"User","text":"Sure. So the biggest challenge was handling WebSocket connections at scale. Initially I was storing all the connections in memory but when I tried to test with multiple users it would crash. So I refactored it to use Redis as a pub sub layer which helped manage the connections across multiple server instances."},{"speaker":"Gemini","text":"Solid approach using Redis for pub/sub. That shows good architectural thinking. Now, tell me about a time you had to work on a team project where there was a disagreement. How did you handle it?\n"},{"speaker":"User","text":"In one of my group projects we had a disagreement about whether to use REST or GraphQL for our API. I suggested we list out the pros and cons for our specific use case and we ended up going with REST since our data wasn''t deeply nested. Everyone was on board after that."},{"speaker":"Gemini","text":"That''s a really pragmatic way to resolve it. I appreciate the data-driven approach. Well, I think that covers what I wanted to discuss today. Thank you so much for your time and thoughtful answers. Have a great day!\n"}]',
  '{"grade":7,"summary":"The candidate communicated clearly and showed solid practical engineering judgment, especially when discussing Redis pub/sub and architectural trade-offs.","sections":[{"title":"Communication Skills","content":"The candidate communicated clearly and concisely throughout the interview. Answers were well-structured and easy to follow. However, some responses could benefit from more specific metrics or outcomes. Suggestion: include numbers like `tested with 50+ concurrent users` to quantify impact."},{"title":"Technical Depth","content":"Strong understanding of architectural patterns demonstrated through the Redis pub/sub solution. The candidate showed practical knowledge of real-time systems. The REST vs GraphQL answer was good, but could have gone deeper into the technical trade-offs considered."},{"title":"STAR Method Usage","content":"The candidate naturally followed the Situation-Task-Action-Result framework in some answers but missed stating explicit results in others. Suggestion: always close with a measurable result, such as the project outcome after choosing REST."}]}'
 );

-- Interview 2: Full-Stack Developer at Amazon (score 9)
INSERT INTO interviews (user_id, typeofinterview, institution, score, interview_date)
VALUES (1, 'new-grad', 'Amazon', 9, '2026-03-21');

INSERT INTO QAOfInterview (interview_id, chat, feedback)
 VALUES (
  (SELECT id FROM interviews WHERE user_id = 1 AND institution = 'Amazon' AND score = 9),
  '[{"speaker":"Gemini","text":"Hello! I''m Jordan, a hiring manager on the retail platform team at Amazon. Welcome to your interview for the Full-Stack Developer position. Let''s get started — can you tell me about yourself and what interests you about this role at Amazon?\n"},{"speaker":"User","text":"Thanks Jordan. I recently graduated with a degree in computer science and I''ve spent the last year working on a startup project where I built the entire stack from a React front end to a Node and PostgreSQL backend. What excites me about Amazon is the scale. I want to work on systems that serve millions of users and I think the challenges here would really accelerate my growth as an engineer."},{"speaker":"Gemini","text":"That''s a compelling reason. Building a full stack from scratch is impressive. Can you describe a situation where you had to optimize performance in one of your applications?\n"},{"speaker":"User","text":"Definitely. Our app had a dashboard that was loading slowly because it was making twelve separate API calls on mount. I implemented a batched query endpoint on the backend that combined related queries into a single round trip, and added Redis caching for data that didn''t change frequently. Load time dropped from 4.2 seconds to under 800 milliseconds. Users noticed immediately and our retention on that page went up by about 30 percent."},{"speaker":"Gemini","text":"Excellent results with concrete metrics. That''s exactly the kind of customer-obsessed thinking we value. Tell me about a time you received critical feedback and how you responded to it.\n"},{"speaker":"User","text":"During a code review my mentor pointed out that my error handling was inconsistent across the codebase. Some endpoints returned proper error objects while others just threw generic 500s. I took it seriously and spent a weekend creating a centralized error handling middleware with standardized error codes and messages. After that our debugging time dropped significantly and my mentor actually adopted the pattern for his own projects."},{"speaker":"Gemini","text":"That shows great ownership and a growth mindset. Thank you for sharing those examples. I''ve really enjoyed our conversation today. Have a great day!\n"}]',
  '{"grade":9,"summary":"The candidate was highly articulate, technically strong, and consistently supported answers with concrete metrics and clear outcomes.","sections":[{"title":"Communication Skills","content":"Exceptional communication throughout. The candidate provided clear, structured answers with specific details and quantifiable outcomes. Every response demonstrated confidence and professionalism."},{"title":"Technical Depth","content":"Outstanding technical knowledge demonstrated across frontend optimization, backend architecture, caching strategies, and error handling patterns. The batched query optimization answer was particularly strong with concrete metrics such as `4.2s to 800ms` and `30% retention improvement`."},{"title":"STAR Method Usage","content":"Near-perfect use of the STAR framework. Each answer included a clear Situation, Task, Action, and measurable Result. The error handling answer naturally flowed through all four components."},{"title":"Areas for Minor Improvement","content":"Could mention specific AWS services or Amazon technologies to show stronger company research. The self-introduction could also include a brief mention of leadership or mentorship experience."}]}'
 );

-- Interview 3: Data Analyst Co-op at TD Bank (score 4)
INSERT INTO interviews (user_id, typeofinterview, institution, score, interview_date)
VALUES (1, 'internship', 'TD Bank', 4, '2026-03-21');

INSERT INTO QAOfInterview (interview_id, chat, feedback)
 VALUES (
  (SELECT id FROM interviews WHERE user_id = 1 AND institution = 'TD Bank' AND score = 4),
  '[{"speaker":"Gemini","text":"Hi! I''m Casey, and I''ll be interviewing you today for the Data Analyst Co-op position in Commercial Banking. We''re excited to learn more about your skills and experience. To start, can you tell me about a project where you worked with data analysis or visualization?\n"},{"speaker":"User","text":"Um yeah so I did a project in school where we had to like analyze some data. It was a CSV file and I used Python to read it and make some graphs. It was okay I guess."},{"speaker":"Gemini","text":"Thanks for sharing. Can you be more specific about what kind of data it was and what insights you were able to draw from your analysis?\n"},{"speaker":"User","text":"It was like sales data I think. We made a bar chart and a line graph. I don''t really remember the details to be honest it was a while ago."},{"speaker":"Gemini","text":"I see. Let me ask you this — tell me about a time you had to meet a tight deadline. How did you manage your time?\n"},{"speaker":"User","text":"I''m not great with deadlines honestly. I usually just try to get things done last minute. It works out most of the time though."},{"speaker":"Gemini","text":"I appreciate your honesty. Well, that wraps up our questions for today. Thank you for coming in. Have a great day!\n"}]',
  '{"grade":4,"summary":"The candidate needs more interview preparation, especially around structured storytelling, technical specificity, and professional framing of weaker areas.","sections":[{"title":"Communication Skills","content":"The candidate struggled to articulate experiences clearly. Responses were vague and lacked structure. Filler words such as `um`, `like`, and `I guess` reduced confidence perception. Suggestion: practice the STAR method and prepare 3-4 stories with specific details, metrics, and outcomes."},{"title":"Technical Depth","content":"Very limited technical depth was demonstrated. The data analysis project description lacked specifics such as libraries used (`pandas`, `matplotlib`), methodologies applied, or insights discovered. A stronger answer would include dataset size, tools, findings, and impact."},{"title":"STAR Method Usage","content":"No STAR framework was followed in any answer. Responses lacked clear situations, actions taken, or results achieved. The deadline management answer was particularly weak with no concrete example provided."},{"title":"Professionalism","content":"The candidate was honest but too casual. Admitting poor deadline management without framing it as a growth area was a missed opportunity. A better framing would explain what systems were adopted to improve reliability over time."}]}'
 );
